name: build py laba

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
      
jobs:
  build_py_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: build py app
        run: |
          python3 Main.py -o first.o
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: py_app
          path: first.o
          retetion-days: 7
